#!/bin/bash

# 1. add http://localhost:3000/login/generic_oauth to redirect URL

TENANT_ID=''
GF_AUTH_GENERIC_OAUTH_CLIENT_ID=''
GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=''

GF_AUTH_BASIC_ENABLED='False'
GF_AUTH_OAUTH_AUTO_LOGIN='True'
GF_AUTH_GENERIC_OAUTH_ENABLED='True'
GF_AUTH_GENERIC_OAUTH_NAME='Azure AD'
GF_AUTH_GENERIC_OAUTH_SCOPES="openid email name"
GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://login.microsoftonline.com/${TENANT_ID}/oauth2/authorize
GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://login.microsoftonline.com/${TENANT_ID}/oauth2/token

docker run -d -p 3000:3000 -e "GF_AUTH_GENERIC_OAUTH_ENABLED=$GF_AUTH_GENERIC_OAUTH_ENABLED" \
   -e "GF_AUTH_BASIC_ENABLED=$GF_AUTH_BASIC_ENABLED" \
   -e "GF_AUTH_GENERIC_OAUTH_NAME=$GF_AUTH_GENERIC_OAUTH_NAME" \
   -e "GF_AUTH_OAUTH_AUTO_LOGIN=$GF_AUTH_OAUTH_AUTO_LOGIN" \
   -e "GF_AUTH_GENERIC_OAUTH_CLIENT_ID=$GF_AUTH_GENERIC_OAUTH_CLIENT_ID" \
   -e "GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=$GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET" \
   -e "GF_AUTH_GENERIC_OAUTH_SCOPES=$GF_AUTH_GENERIC_OAUTH_SCOPES" \
   -e "GF_AUTH_GENERIC_OAUTH_AUTH_URL=$GF_AUTH_GENERIC_OAUTH_AUTH_URL" \
   -e "GF_AUTH_GENERIC_OAUTH_TOKEN_URL=$GF_AUTH_GENERIC_OAUTH_TOKEN_URL" \
   --rm --name grafana grafana/grafana


